### ISSUE TITLE
Tutorial link not available

### ISSUE THREAD

**Issue by alouis72** [DessimozLab/pyham#21]
Hi,
is the tutorial available elsewhere than http://zoo.cs.ucl.ac.uk/tutorials/tutorial_pyHam_get_started.html  (at the present time, got an Internal Server error)??

I'm trying to use pyham to parse HOGS data but I have some problems understanding the structures of objects.
Best,
Alex

**Comment by F4llis** [comment]
Hello, 

The server is down for some reasons but I contacted the person responsable for it and it should be restarted. In the meanwhile I can send you the tutorial by email if you want ! (clement.train@gmail.com)

**Comment by alouis72** [comment]
Thank you Clement for your quick answer, 
I've just sent you an email.
