### ISSUE TITLE
Treeprofile displaying help but no tree

### ISSUE THREAD

**Issue by ak-watson** [DessimozLab/pyham#6]
I was looking through the sample jupyter notebook for pyham and noticed that the treeprofile view appears to be broken at the moment.

The same applies to my own jupyter notebook.

The following issues are raised when loading the output html file, based on failure to load javascript resources. 

Both cases are "HTTP/2 301" redirects

Thanks for any help! 

`
Failed to load resource: net::ERR_TOO_MANY_REDIRECTS https://cdn.rawgit.com/DessimozLab/phylo-io/5e89fafc3b1746b22da33c20b2af621d5807b6fb/www/js/d3.min.js

Failed to load resource: net::ERR_TOO_MANY_REDIRECTS
treecompare.js:4082 
https://cdn.rawgit.com/DessimozLab/phylo-io/5e89fafc3b1746b22da33c20b2af621d5807b6fb/www/js/FileSaver.min.js

Uncaught ReferenceError: d3 is not defined
    at TreeCompare (treecompare.js:4082)
    at tp.html:66
`

**Comment by ak-watson** [comment]
Just to add to my previous comment, I guess the failure of resources to load is down to some sort of server issue.

I managed to work through the errors by replacing with alternative links to FileSaver.min and d3.min (though I'm not sure they are the same version that was intended).

This got me through to another error from treecompare.js imported from phylo-io

`Uncaught TypeError: Cannot read property 'tree' of undefined
    at renderTree (treecompare.js:4966)
    at Object.viewTree (treecompare.js:5702)
    at tp.html:75` 

I have tried a couple of things to resolve it, but no luck so far. As far as I can see, the html file calls treecompare correctly (according to the phylo-io manual). I suspected my tree itself might have been the issue, so I replaced the variable tree1 with the example from the phylo-io manual.

`var tree1 = treecomp.addTree("(D:0.3,(C:0.2,(A:0.1,B:0.1):0.1):0.1);", undefined, "single"); 
`
Unfortunately I still come up with the same error.

**Comment by F4llis** [comment]
Hello,

The issue with the libraries is now fixed (version 1.1.8).

Regarding the second issue, I tried your newick tree using https://phylo.io/ and it works fine. Could you please shared your html file so I can debug it ? 

Thx,
Clement

**Comment by ak-watson** [comment]
Hi Clement, 

Thanks for the response, the newick tree was working fine on the phylo.io website for me as well, sorry for the misunderstanding. I was only having an issue with the html. I'll update to 1.1.8 and check if the problem is still there. I'll send the html if i still have the problem.

Thanks again,
Andrew
